name: cpp_lint

# lint on c/cpp changes or workflow changes
on:
  push:
  pull_request:
env:
  CLANG_TIDY: clang-tidy-15

jobs:
  clang_tidy:
    runs-on: ubuntu-22.04
    steps:
    - name: Disable parallel checkout (avoids a git race that can fail with 'unable to create symlink')
      run: git config --global checkout.workers 1
    - uses: actions/checkout@v4
    - name: Install deps
      run: |
        source ./util/ci/common.sh
        install_linux_deps $CLANG_TIDY

    - name: Run clang-tidy
      run: |
        ./util/ci/clang-tidy.sh
